# Generated by Django 2.2.4 on 2019-11-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=400)),
                ('cpu_model_no', models.CharField(max_length=400)),
                ('mobo_brand', models.CharField(max_length=400)),
                ('cpu_tdp', models.IntegerField()),
                ('cpu_gen', models.IntegerField()),
                ('cpu_unit_price', models.IntegerField()),
                ('cpu_quantity', models.IntegerField()),
                ('supported_chipset', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobo_name', models.CharField(max_length=400)),
                ('mobo_model_no', models.CharField(max_length=400)),
                ('chipset', models.CharField(max_length=400)),
                ('mobo_brand', models.CharField(max_length=400)),
                ('mobo_tdp', models.IntegerField()),
                ('mobo_unit_price', models.IntegerField()),
                ('mobo_quantity', models.IntegerField()),
                ('mobo_size', models.CharField(max_length=400)),
                ('supported_ram_type', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=400)),
                ('ram_model_no', models.CharField(max_length=400)),
                ('ram_brand', models.CharField(max_length=400)),
                ('ram_tdp', models.IntegerField()),
                ('cpu_type', models.IntegerField()),
                ('ram_unit_price', models.IntegerField()),
                ('ram_quantity', models.IntegerField()),
            ],
        ),
    ]
