# Generated by Django 2.2.4 on 2019-11-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='mobo_brand',
            new_name='cpu_brand',
        ),
    ]
