# Generated by Django 2.2.4 on 2019-11-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191123_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='cpu_type',
        ),
    ]
